### ISSUE TITLE
Publishing is broken

### ISSUE THREAD

**Issue by ber4444** [okta/okta-idx-java#258]
2.0.0 did not make it to https://search.maven.org/artifact/com.okta.idx.sdk/okta-idx-java-api

**Comment by VitaliiTytarenko-okta** [comment]
Hello, @ber4444 
I didn't get you. Could you explain what you are trying to do, please?

**Comment by arvindkrishnakumar-okta** [comment]
@ber4444 Thanks for reporting this. The artifact was staged but didn't get pushed to maven central. I'll get this fixed.

**Comment by arvindkrishnakumar-okta** [comment]
This has just been released from staging env, and should appear in Maven central in the next 2-3 hours approx.

**Comment by ber4444** [comment]
5 hrs passed and still not there, will keep waiting

**Comment by arvindkrishnakumar-okta** [comment]
@ber4444 sorry abt that, I'll check with the staging repo support team.

**Comment by arvindkrishnakumar-okta** [comment]
@ber4444 the 2.00 artifacts should now be available on Maven: https://repo1.maven.org/maven2/com/okta/idx/sdk/
