### ISSUE TITLE
User-Agent is hard coded

### ISSUE THREAD

**Issue by bdemers** [okta/okta-idx-java#301]
See:
https://github.com/okta/okta-idx-java/blob/1f2af5eccb6cc7534687f3c5a0f5a8b3da238a45/api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java#L71

The version _should_ get picked up automatically if you include an `META-INF/okta/version.properties` file

For example:
https://github.com/okta/okta-jwt-verifier-java/blob/c3e44c142472fe34e6eaac1443b9a75f7c2e7368/impl/src/main/resources/META-INF/okta/version.properties

And enabler version filtering in the pom:
https://github.com/okta/okta-jwt-verifier-java/blob/c3e44c1/impl/pom.xml#L123-L129

**Comment by arvindkrishnakumar-okta** [comment]
Will be fixed as part of #329
