### ISSUE TITLE
Add support for UserInfo Endpoint

### ISSUE THREAD

**Issue by bdemers** [okta/okta-idx-java#302]
The current embedded auth sample requires the user to configure the issuer twice, and create an additional HTTP client (which may have different timeouts/proxy settings, etc)

Direct support should be added to this client.

**Comment by arvindkrishnakumar-okta** [comment]
We do not plan to add `UserInfo` to IDX SDK at this point. We could use the Mgmt SDK/OIDC SDK to achieve this. We use `userinfo` just to validate if the login was successful.
