### ISSUE TITLE
getting null pointer exception when we give the wrong OTP for more than 5 times

### ISSUE THREAD

**Issue by jkprerana** [okta/okta-idx-java#397]
While verifying the email/phone OTP, when we give wrong OTP for more than 5 times, we are getting null pointer exception.

I observed that in BaseIDXClient.java Line 597 we are getting this error.

Current code is : _response.getHeaders().getContentType() != null && response.getHeaders().getContentType().toString().contains("application/json") || response.getHeaders().getContentType().toString().contains("application/ion+json")_

Actual code should be: _response.getHeaders().getContentType() != null && (response.getHeaders().getContentType().toString().contains("application/json") || response.getHeaders().getContentType().toString().contains("application/ion+json"))_

Also is it possible to get meaningful messages when we get 429 error from the APIs when we are trying to verify the OTP?
Currently, we are getting this error: _Request to https://xxxxx/idp/idx/challenge/answer failed. HTTP status: 429_
Previously we were getting a different message like _Max tries reached._

**Comment by arvindkrishnakumar-okta** [comment]
@jkprerana we welcome PRs, if you can submit a PR with the change it'll be much appreciated.

429 is a Okta backend error you get when you have submitted too many requests exceeding the rate limit.
