### ISSUE TITLE
Unexpected end of stream error

### ISSUE THREAD

**Issue by GayathriGouni5** [okta/okta-idx-java#445]
Hi, We are using Okta IDX SDK (version: 3.0.4) for auth and MFA in our android app. In both production & QA, we see the following particular error happening quite often:
com.okta.commons.http.HttpException: unexpected end of stream on https://qa.login.***.com. It’s thrown from Okta SDK functions.
This error has been thrown from Okta SDK functions, mostly when calling SDK to send challenge code to a selected factor (after userid/pass verified), secondly when calling SDK to verify the entered OTP. The SDK login call with userId/pass also recorded such error (less frequent than the other two).
Once getting such error, retrying the operation again seems to help. Close and reopen the app seems can help.

Please find the details and STR for one of the scenarios below:
Steps to reproduce:
Log in with username/password .
After successful idxAuthenticationWrapper.verifyAuthenticator(
	authResponse.proceedContext,
	VerifyAuthenticatorOptions(password)
) call, which returns two options email and mobile. 
Click on either options really quick and this calls select Authenticator IDXAuthenticationWrapper.selectAuthenticator(ProceedContext proceedContext,com.okta.idx.sdk.api.client.Authenticator authenticator).

Issue:
Getting the below exception
com.okta.commons.http.HttpException: unexpected end of stream on  https://qa.login.***.com/..

Please advise if it’s a known issue. Any help/ directions to fix this issue is appreciated.

Thank you!

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!

I'm working on investigating this issue, will send an update once I have it.

**Comment by arvindkrishnakumar-okta** [comment]
Fix available in release version 3.0.6.
