### ISSUE TITLE
Could not find artifact com.okta.idx.sdk:okta-idx-java-api:jar:3.0.7-SNAPSHOT

### ISSUE THREAD

**Issue by literallyjustroy** [okta/okta-idx-java#456]
```shell
[ERROR] Failed to execute goal on project okta-idx-java-embedded-sign-in-widget: Could not resolve dependencies for
project com.okta.idx.sdk:okta-idx-java-embedded-sign-in-widget:jar:3.0.7-SNAPSHOT: The following artifacts could not be
resolved: com.okta.idx.sdk:okta-idx-java-api:jar:3.0.7-SNAPSHOT (absent): Could not find artifact com.okta.idx.sdk:okta
idx-java-api:jar:3.0.7-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
```

It appears this artifact isn't in the repo:
<img width="488" alt="image" src="https://github.com/okta/okta-idx-java/assets/56088145/7c12098a-4389-4470-889a-ca607e7501c9">

For now I just changed the `pom.xml` to reference 3.0.6.

**Comment by arvindkrishnakumar-okta** [comment]
`3.0.7-SNAPSHOT` is a development snapshot version and you will not find it in artifactory.

Can you do a `mvn clean install` from the project root and then run the sample sign-in-widget?
